### PR TITLE
quick fix for importing canals

### PR DESCRIPTION
**Pull request by Idhrendur**

### CODE REVIEW

**Comment by IhateTrains** [comment]
This is for older EU versions compatibility, right?

**Comment by Idhrendur** [comment]
Yes. I had noticed new versions were getting parse errors. Without this, I would expect canals to not convert. With it, they should.

**Comment by IhateTrains** [comment]
Sounds strange, I will investigate by adding some logging.

**Comment by IhateTrains** [comment]
So after adding logging I converted my 1.28 save and a 1.19 save from the repo. They both used the part I added. Could you check it again, or at least upload the save you used?

**Comment by EcceTestudo** [comment]
are there any test saves with canals? I can test for regular converts to see if it messes anything up but believe we'd need a test save w/ canals.

**Comment by Idhrendur** [comment]
I'm not sure. I just recall seeing warnings in the log about parse errors when debugging other people's saves. I don't recall which saves at this point.

**Comment by EcceTestudo** [comment]
we can always get a fresh save I suppose. I can work on generating one in the next couple days, shouldn't be too hard.

**Pull request closed without merging**
