### PR TITLE
Iohannes' PR without tons of unchanged files v2

### PR DESCRIPTION
**Pull request by IhateTrains**
According to @IohannesIohannium:

- Fixed spawn of Egypt from the Turks
- Make (at start) Krakow spawn from Austria, Montenegro in Cetinje, St-Pierre-and-Miquelon to the holder of Caen
- Fixed Shimla and Zulu events rehappening
- Fixed Dominican Republic start cores
- Fixed Dominican Republic independence event to happen also under Haiti
- Make event to turn UK into ENG or SCO if any of the two exists independent
- Make the three Boer republics request independence
- Santo Domingo (Saint Dominick) renaming decisions
- ENG_13 (British Columbia) rename default as simply Columbia
- Ternate will no longer overlap with Transvaal
- Further new tags added (e.g. Sudetenland, Inner Mongolia)
- Fixed Senegal-Songhai overlap
- Added decision to fix nogovernments at start (best I can do for a moment)

### CODE REVIEW

**Comment by IhateTrains** [comment]
Should configuration.txt also be reverted?

**Comment by Idhrendur** [comment]
Better if it is. It's annoying otherwise.

**Comment by IhateTrains** [comment]
Done.
There are lots of differences in province mappings but it's not even mentioned in the list of changes, may it mean that it comes from an old version of the main repo?

**Comment by Idhrendur** [comment]
It could have been. It's worth double-checking, at least.

**Comment by Idhrendur** [comment]
I'm looking at it,and the updated province mappings did something weird. I'll revert it to the previous ones.

**Pull request merged**
