### PR TITLE
Fix infinite loop curing army conversion

### PR DESCRIPTION
**Pull request by Idhrendur**
Addresses #237 (there's a save attached to the bug).

Also includes some code cleanup. Should have no other effects on conversion.

### CODE REVIEW

**Comment by IhateTrains** [comment]
I will test it.

**Comment by IhateTrains** [comment]
On master the loop occurs, on the PR branch it completed successfully. Should I check anything else?

**Comment by Idhrendur** [comment]
Sounds good! The resulting mods lead in Vic 2 and don't have any obvious errors, right?

**Comment by IhateTrains** [comment]
The mod looks fine in Vicky:
image

What do you mean by "The resulting mods lead in Vic 2"?

**Comment by Idhrendur** [comment]
I meant load, sorry. Thanks for testing!

**Pull request merged**
