### PR TITLE
Canals fix

### LINKED ISSUE #11: Convert Canals
DasGuntLord01 figured out how to put them in Vic2: http://forum.paradoxplaza.com/forum/showthread.php?707362-The-EU4-to-V2-Converter-Project&p=18921501&viewfull=1#post18921501

### PR DESCRIPTION
**Pull request by IhateTrains**
Once this is merged, #11 can be closed again.

### CODE REVIEW

**Comment by Idhrendur** [comment]
Two things:
1. Great projects should go into new .cpp/.h files. 
2. I'm not familiar with the format for it, but you might be leaking tokens by not using ignorItem. Is there anything in the log?

**Comment by IhateTrains** [comment]
I removed ignoreItem because there is no "=yes' after the canal name, unlike in the buildings. The log seems fine.

**Comment by Idhrendur** [comment]
Ah, that's exactly correct, then.

Looks like the new .cpp file also need sto be added to the tests. And for that matter, You should write some tests for the GreatProjects class.  I think there's some buildings ones you can just copy (and adjust to be correct to the file format).

**Comment by IhateTrains** [comment]
Done, although I'm editing tests for the first time, so something may be wrong.

**Comment by Idhrendur** [comment]
Wonderfully done!

**Comment by IhateTrains** [comment]
I'm working on simplifying the hasGreatProject function usage and getting two of the tests to actually work, will make a small hotfix PR as soon as it's done.

**Pull request merged**
