### PR TITLE
Iohannes' PR without tons of unchanged files

### PR DESCRIPTION
**Pull request by IhateTrains**
Accoding to @IohannesIohannium:

- Fixed spawn of Egypt from the Turks
- Make (at start) Krakow spawn from Austria, Montenegro in Cetinje, St-Pierre-and-Miquelon to the holder of Caen
- Fixed Shimla and Zulu events rehappening
- Fixed Dominican Republic start cores
- Fixed Dominican Republic independence event to happen also under Haiti
- Make event to turn UK into ENG or SCO if any of the two exists independent
- Make the three Boer republics request independence
- Santo Domingo (Saint Dominick) renaming decisions
- ENG_13 (British Columbia) rename default as simply Columbia
- Ternate will no longer overlap with Transvaal
- Further new tags added (e.g. Sudetenland, Inner Mongolia)
- Fixed Senegal-Songhai overlap
- Added decision to fix nogovernments at start (best I can do for a moment)

### CODE REVIEW

**Comment by Idhrendur** [comment]
The changes to Eu4ToVic2DefaultConfiguration.xml and SupportedConvertersDefault.xml should be reverted, otherwise they'll break the configuration.

**Comment by Idhrendur** [comment]
And if it's not too much effort, it'd be nice if the files that were just line ending changes were removed from this too. But that one's fairly minor.

**Comment by IhateTrains** [comment]
I've noticed some remaining files with just line ending changes in decisions and event, this will be fixed.

**Comment by IhateTrains** [comment]
Created a new PR: #199

**Pull request closed without merging**
